# Default initial positions for allegro_hand_right's ros2_control fake system

initial_positions:
  joint_0.0: 0
  joint_1.0: 0
  joint_10.0: 0
  joint_11.0: 0
  joint_12.0: 0
  joint_13.0: 0
  joint_14.0: 0
  joint_15.0: 0
  joint_2.0: 0
  joint_3.0: 0
  joint_4.0: 0
  joint_5.0: 0
  joint_6.0: 0
  joint_7.0: 0
  joint_8.0: 0
  joint_9.0: 0