# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    allegro_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    thumb_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    index_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    middle_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ring_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    index_tip_controller:
      type: position_controllers/GripperActionController


    thumb_tip_controller:
      type: position_controllers/GripperActionController


    middle_tip_controller:
      type: position_controllers/GripperActionController


    ring_tip_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

allegro_hand_controller:
  ros__parameters:
    joints:
      - joint_0.0
      - joint_1.0
      - joint_2.0
      - joint_3.0
      - joint_12.0
      - joint_13.0
      - joint_14.0
      - joint_15.0
      - joint_4.0
      - joint_5.0
      - joint_6.0
      - joint_7.0
      - joint_8.0
      - joint_9.0
      - joint_10.0
      - joint_11.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
thumb_controller:
  ros__parameters:
    joints:
      - joint_12.0
      - joint_13.0
      - joint_14.0
      - joint_15.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
index_controller:
  ros__parameters:
    joints:
      - joint_0.0
      - joint_1.0
      - joint_2.0
      - joint_3.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
middle_controller:
  ros__parameters:
    joints:
      - joint_4.0
      - joint_5.0
      - joint_6.0
      - joint_7.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
ring_controller:
  ros__parameters:
    joints:
      - joint_8.0
      - joint_9.0
      - joint_10.0
      - joint_11.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
index_tip_controller:
  ros__parameters:
    joints:
      []
thumb_tip_controller:
  ros__parameters:
    joints:
      []
middle_tip_controller:
  ros__parameters:
    joints:
      []
ring_tip_controller:
  ros__parameters:
    joints:
      []